### ISSUE TITLE
Investigate support for TR143

### ISSUE THREAD

**Issue by jarlah** [freeacs/freeacs#208]
https://www.broadband-forum.org/technical/download/TR-143.pdf
https://www.qacafe.com/training/performance-monitoring-using-tr-143/
https://cwmp-data-models.broadband-forum.org/tr-143-1-1-0.html
mikrotik specific:
https://wiki.mikrotik.com/tr069ref/current.html#Device.

**Comment by jarlah** [comment]
Summary. Its going to a tough job without someone who knows this diagnostics protocol intimately.

**Comment by jarlah** [comment]
@kangdengfeng 
We need to cover a minimal viable product, one use case to be precise. I have read the documents, but they are very technical and does not exactly show the xml payloads back and forth.

Whats the most common usage you can think of?
How is the use case initiated by the ACS or CPE?
What kind of RPC methods (soap) is involved?
Or, what parameters to set to initiate the diagnostics?

All in all, since I must rely on domain experts, I need to see examples on how the protocol looks like in xml payloads or similar pseudo payloads described with words.

**Comment by penaivanalejandro** [comment]
> @kangdengfeng
> We need to cover a minimal viable product, one use case to be precise. I have read the documents, but they are very technical and does not exactly show the xml payloads back and forth.
> 
> Whats the most common usage you can think of?
> How is the use case initiated by the ACS or CPE?
> What kind of RPC methods (soap) is involved?
> Or, what parameters to set to initiate the diagnostics?
> 
> All in all, since I must rely on domain experts, I need to see examples on how the protocol looks like in xml payloads or similar pseudo payloads described with words.

What is the most common use you can imagine?

- We use to measure the speed or width of the CPE band to the Internet and be proactive before the client informs us of any slowness in their service.

How is the use case initiated by the ACS or CPE?
- It is initiated by the ACS setting the parameters so that the CPE begins to perform the test. (attached image).
![tr-143](https://user-images.githubusercontent.com/29745524/48921200-b6bfdb80-ee63-11e8-8630-c7e0095e43f1.png)
More Info: https://www.broadband-forum.org/technical/download/TR-143.pdf

What kind of RPC methods are involved?
- First, identify the paremtros (RW) the requirements to set and maintain their values ​​(eg, if the test is to download HTTP, the URL where the file is to be downloaded, etc ...)
- We also have to enable the read parameters to wait for the results from the CPE.
- Then it is to execute the kick to the CPE with the previously activated parameters and wait for the CPE to execute the test and return the results to FreeACS.


Or, what parameters to configure to start the diagnosis?
Or, what parameters to configure to start the diagnosis?
- I confirm the parameters, tests with a team and I confirm you.
Or the other one here you can find the values ​​that have to be sent to the CPE (RW) and the values ​​that you will expect to read (R) when finished.
https://cwmp-data-models.broadband-forum.org/tr-143-1-1-0.html


And an apology had had me doing provisioning tests with the ACS and had not had an opportunity to enter the forum.

**Comment by jarlah** [comment]
@kangdengfeng That sounds very much like the process we need to support. The problem however, is which parameters to set in SPV. CPE diagnostics can be a broad subject. And if you have a very minimal example of for example a couple of parameters that, following the TR143 spec, can be used to initiate some basic diagnostics for a device, then I can investigate how this can be implemented.

The graphical interface as it is now, is not very extendable. Its actually not something I would like to modify. Therefore I am thinking in the lines of making a new set of graphical user interfaces for doing things like diagnostics. The problem with parameters as it is now, is its very tedious to configure the parameters, and it must be done very manually through jobs and groups and what not. 

What if we could make an interface that guides you through the steps for activating diagnostics for a single or multiple devices? What would that interface look like? Is there any examples out there in other acs interfaces that we could borrow ideas from?

**Comment by kangdengfeng** [comment]
Ok , i think  know your confusion~~I will sort out the process of this part first.
