### ISSUE TITLE
how do i set a cpe's connection request username and password with freeacs

### ISSUE THREAD

**Issue by techdpnn** [freeacs/freeacs#311]
hi, fellas~

**Comment by techdpnn** [comment]
i have just installed freeacs in unbuntu 18. 
but how can i set a cpe's connection request username and password?
there are some communications between freeacs and my cpe ,i can see that by wireshark .

acs adress is 192.168.0.103 , cpe is 192.168.0.101
![Screenshot from 2019-04-12 14-43-55](https://user-images.githubusercontent.com/49048026/56017366-9cfb3400-5d31-11e9-8d33-ded27f8d5bd7.png)

**Comment by pingwiniasty** [comment]
Connection Request username and password are configured in cpe by default, and You need to add cpe manually to ACS and provide correct password. But you can also configure tr069 module with `discovery.mode =  true` and cpe will be added autmaticly

**Comment by techdpnn** [comment]
@pingwiniasty  thanks for response.
i have configured discovery.mode = true and my cpe was found in freeacs.
However,they can only do inform communication between cpe and freeacs.
I think , if freeacs want to send message to cpe by `connection request url`, there should be a authorize with username and password. and Wireshark message above proved that

**Comment by techdpnn** [comment]
the exact parameter name is `InternetGatewayDevice.ManagementServer.ConnectionRequestURL`

**Comment by pingwiniasty** [comment]
Ok. In unit configuration, below colum named "Unit value" select "all" from combobox and try to find ConnectionRequestUsername and ConnectionRequestPassword. If it not exist you can this parameter manually in Unit Type and configure its value in Unit Profile or Unit

**Comment by techdpnn** [comment]
i have added these two parameter,and set their flag to 'RW', it  didn't work.
then i tried set flag to "X", Wireshark( a network protocol analyze tool ) tips "unauthorized".
in a word , it didn't work.

**Comment by pingwiniasty** [comment]
Could you attach `tr069-conversation.log` here?

**Comment by techdpnn** [comment]
[tr069-conversation.log](https://github.com/freeacs/freeacs/files/3072246/tr069-conversation.log)

**Comment by vasqude** [comment]
I have a similar question to this. How can we make it so that the ACS automatically populates these values from the CPE?
 I can verify that the CPE is sending the information but I still have to manually create the parameter. What do we need to change so that when a new CPE contacts the ACS the ACS populates the Connection Request username, password, and URL? Other parameters are auto-populated as shown below. 

![auto_populated_parameters_](https://user-images.githubusercontent.com/49952193/56835625-5a118400-683a-11e9-943a-cae5d79fab37.PNG)

**Comment by jarlah** [comment]
you can set RA flag on the unittype parameters. Then they will be requested read from the cpe by the acs. Other params are system parameters and are handled specially.

**Comment by vasqude** [comment]
Jarlah -

Thank you for your response, the issue that I am seeing now is that once I changed the flag from RW to RA on the ConnectionRequest username, password and URL parameters. The conversation between CPE and  ACS doesn't stop. The TCP dumps show that the 204 code is sent and then immediately the conversation begins all over again. Is this an issue or have you seen this before? It does impact provisioning I cannot send new values since the initial conversation has not ended.

**Comment by vasqude** [comment]
I found the issue, the InternetGatewayDevice.ManagementServer.PeriodicInformInterval value keeps changing, therefore, causing the conversation to be stuck in a loop. What do we need to change to make this correction? 

![periodicInformInterval](https://user-images.githubusercontent.com/49952193/56875756-62b7b500-6a08-11e9-9feb-e93a256b0399.PNG)

**Comment by jarlah** [comment]
@techdpnn endless tries from the cpe to call GetRPCMethods. Not supported currently. But dont fret :) its supported on master. I just need to stabilize master and make a release. Cant give a date though. But its at least one of the next weeks
